### ISSUE TITLE
JSON returned by myCtmSession.deploy_api.get_deployed_folders_new() is not a valid JSON

### ISSUE THREAD

**Issue by arturiwan** [controlm/ctm-python-client#10]
string returned by `Session.deploy_api.get_deployed_folders_new()` is not a valid JSON.
It contains single 'apostrophes' instead of double "quotes".
So the returned string is in the format
```{'xxx': {'Type': 'SimpleFolder', 'ControlmServer': 'yyy', ...}}```
but should be:
```{"xxx": {"Type": "SimpleFolder", "ControlmServer": "yyy", ...}}```

More details inside BMC case 01403669

**Comment by cmoraes-bmc** [comment]
Hi, 
Thanks for the feedback. Current the use case for python client is not to import deployed jobs. When this use case will be added, we will add a wrapper on the "get_deployed_folders_new" to transform it to json

Thanks
