### ISSUE TITLE
monitor.get_statuses returns an object instead of a dict

### ISSUE THREAD

**Issue by dcompane** [controlm/ctm-python-client#17]
**Is your feature request related to a problem? Please describe.**
The status returned should be a dict to ensure clarity when querying the results. Otherwise, since there is no specific documentation, it takes a lot of effort to find how to query the results.

**Describe the solution you'd like**
to be able to query the results of get_statuses as a dict.

**Describe alternatives you've considered**

**Additional context**
f"Folder Name                 : {status.statuses[0].folder} " 

I was expecting I would need to do
f"Folder Name                 : {status['statuses'][0]['folder']} " (or alike)

**Comment by cmoraes-bmc** [comment]
as designed - this is the result object that comes directly from the api
