### ISSUE TITLE
Submit ctm-python-client to PyPi

### ISSUE THREAD

**Issue by dcompane** [controlm/ctm-python-client#26]
**Is your feature request related to a problem? Please describe.**
Add the package to PyPi

**Describe the solution you'd like**
I want to be able to use PyPi as the source, instead of github.

**Describe alternatives you've considered**
Not sure what would be an alternative to PyPi.

**Additional context**
Organizations wanting to access the client can find it and know that it is the appropriate package.

**Comment by Galgc** [comment]
we plan to sync the project with PyPi as part of the comming monthly release of Automation API (June 2023).
@RefaelBeker7 will update with the link, and close once published.
