### ISSUE TITLE
Missing examples/docs for job events (WaitForEvents, AddEvents, DeleteEvents

### ISSUE THREAD

**Issue by wzaremba** [controlm/ctm-python-client#28]
The Docs are missing documenting this features. 
I have created the working example, but I needed to do a reveres engineering:

job1.add_events_list=[AddEvents('eventsToAdd', events=[{"Event" : "wza-event-2"}])]
job1.wait_for_events_list=[WaitForEvents('eventsToWaitFor', events=[{"Event" : "wza-event-wait"}])]

This should be documented at least.

**Comment by dcompane** [comment]
The model seems to be incomplete. There doe snot seem to be a way to indicated AND/OR events in the current implementation.

**Comment by yehonatan-bauminger** [comment]
Event Documentation was added
