### ISSUE TITLE
Easier work with Events

### ISSUE THREAD

**Issue by wzaremba** [controlm/ctm-python-client#29]
I would like to have set of wrappers to work with Events. 
Right now you have to put the following code (as an example) to add/wait for events:

job1.add_events_list=[AddEvents('eventsToAdd', events=[{"Event" : "wza-event-2"}])]
job1.wait_for_events_list=[WaitForEvents('eventsToWaitFor', events=[{"Event" : "wza-event-wait"}])]

Can we add a function wrapper to manage this? Like:
job1.add_wait_for_event("name", "ODAT")
job1.add_event("name", "ODAT")

Of course the function names should be different, or we should add one function with parameters.

**Comment by dcompane** [comment]
The model seems to be incomplete. There does not seem to be a way to indicate AND/OR events in the current implementation.
