### ISSUE TITLE
Add to docs minimum python version required

### ISSUE THREAD

**Issue by dcompane** [controlm/ctm-python-client#31]
**Is your feature request related to a problem? Please describe.**
There is no reference tio what is the minimum python version required

**Describe the solution you'd like**
Add to the README.md the relevant information on requirements,

**Describe alternatives you've considered**
None that I could think of.

**Additional context**
When finding problems, we do not know if it is because there are features used on later versions.

**Comment by rbeker-BMC** [comment]
Added
