### ISSUE TITLE
ctm_python_client library files issue

### ISSUE THREAD

**Issue by spabbise** [controlm/ctm-python-client#34]
We are trying to use the Control-M Python client, for that we have followed the steps mentioned in https://controlm.github.io/ctm-python-client/ >> Getting Started with Control-M Python Client and created a workflow python file as mentioned in the page.

But we are getting multiple issues while executing the workflow Python file in my local system.

Below are the errors:
=====================================
spabbise@SPABBISE-M-VJDV ~ % python ejs.py
File "/Users/spabbise/ejs.py", line 17
print('The workflow is valid!')
^
IndentationError: expected an indented block
=====================================
Traceback (most recent call last):
File "/Users/spabbise/ejs_python.py", line 3, in <module>
from ctm_python_client.core.job import JobCommand
ModuleNotFoundError: No module named 'ctm_python_client.core.job'
=====================================
spabbise@SPABBISE-M-VJDV bin % pip install ctm_python_client
ERROR: Could not find a version that satisfies the requirement ctm_python_client (from versions: none)
ERROR: No matching distribution found for ctm_python_client
=====================================

I think the ctm_python_client library is having some issues, Please check and help us in using the Control-M Python client

**Comment by cmoraes-bmc** [comment]
Hi @spabbise - to work with Control-M Python client, please use **pip install ctm-python-client** as described in the documentation. You attempted to run pip install with ctm_python_client (underscores).
For your issue with module name, please refer to the documentation and tutorials. The jobs are located under the module **aapi**
