### ISSUE TITLE
Issues with Python Client on Control-M Rule-Based Calendar & Shout Destination in Actions

### ISSUE THREAD

**Issue by spabbise** [controlm/ctm-python-client#41]
**Issue_1:**
Trying to add Rule-Based Calendar 'FEB' to my Control-M folder using Python Client by giving the below line in the script. But its not working as expected.
when=Folder.When(rule_based_calendars='FEB')
![Screenshot 2023-08-17 at 6 18 23 PM](https://github.com/controlm/ctm-python-client/assets/137033157/6659fa43-7b46-49ae-8761-55f28fb5c6a7)

Every time its showing '_tag' as RBC and its not taking existing RBC in the environment.

Also why its specifying '_tag' rather taking the exact calendar name defined by the user?

**Issue_2:**
Trying to add custom Shout Destination("SHOUT_OTHER") in Actions but its not working through Python Client
![Screenshot 2023-08-17 at 6 20 27 PM](https://github.com/controlm/ctm-python-client/assets/137033157/62cc7064-30ac-40e1-84d8-0ef5c9436337)

Command: destination=ActionNotify.Destination.JobLog

In the place of JobLog we are looking for "SHOUT_OTHER"

**Comment by jfink5** [comment]
If you want to do Notification After Job Completion, then you can add the following to your job object.

`my_job = JobCommand("my_job", command="echo hello", notify_list=[NotifyNotOK("Notify_0",` destination="SHOUT_OTHER", message="")]`

Or if you want to use If Action (ONDO), I would create the Action object first and then add it.  Its not so messy that way.

`my_shout = ActionNotify("DoNotify_0", destination="SHOUT_OTHER", message=""
my_job = JobCommand("my_job", command="echo hello", if_list=[IfCompletionStatus("IfStatus_0", completion_status="NOTOK", do_list=[my_shout])])`

**Comment by jfink5** [comment]
Code block didn't work out so well.  Trying again this way...

my_job = JobCommand("my_job", command="echo hello", notify_list=[NotifyNotOK("Notify_0", destination="SHOUT_OTHER", message="")])

or...

my_shout = ActionNotify("DoNotify_0", destination="SHOUT_OTHER", message="")
my_job = JobCommand("my_job", command="echo hello", if_list=[IfCompletionStatus("IfStatus_0", completion_status="NOTOK", do_list=[my_shout])])

**Comment by spabbise** [comment]
I am actually looking for ONDO ACTION destination as "SHOUT_OTHER"

Can you help me on that by creating a action object or any other way

**Comment by spabbise** [comment]
Thanks @jfink5 

It is working

**Comment by rbeker-BMC** [comment]
Thanks, @jfink5.
Closed.
