### ISSUE TITLE
How to connect two jobs in different sub-folders

### ISSUE THREAD

**Issue by spabbise** [controlm/ctm-python-client#43]
How to use workflow.chain to connect two jobs in different sub-folders

**Comment by spabbise** [comment]
@jfink5 

Please help me with this requirement

**Comment by jfink5** [comment]
Add the jobs and then use the connect method on the workflow with full path to job name.

workflow.connect("root/sub1/job1", "root/sub2/job2")

**Comment by spabbise** [comment]
Thanks @jfink5 

Your sub-folder jobs connect suggestion worked

Is there a way to connect two jobs related to two different folders?

**Comment by spabbise** [comment]
Okay is there a way to explore more on workflow.connect to connect two jobs related to two different root folders?

**Comment by jfink5** [comment]
You may use workflow.connect to create dependencies between jobs in two different roots.  Just get the pathing accurate.

workflow.connect(srcpath="jfi-ex1/subfolder1/jfi-1", destpath="jfi-ex3/jfi-3")

**Comment by spabbise** [comment]
Its working

Thanks @jfink5
