### ISSUE TITLE
Facing python script deploy issue with a normal user

### ISSUE THREAD

**Issue by spabbise** [controlm/ctm-python-client#44]
Hi Team,

I am trying to test the python client script using a normal user credentials (Not an admin user)

The user has required access to view and modify the required folder that I am testing.

But when am trying to deploy the script, its not working properly.
![Screenshot 2023-08-30 at 12 19 31 PM](https://github.com/controlm/ctm-python-client/assets/137033157/c44415e0-8107-44f8-b6e6-5d0213bf40bc)

In Control-M EM , I can see after doing a deploy the folder is going to "Not Synchronized" state.
![Screenshot 2023-08-30 at 12 20 23 PM](https://github.com/controlm/ctm-python-client/assets/137033157/21fa28e9-a099-4e5f-9fd8-9f8ea2ed7f81)

Please help me in fixing this issue.

**Comment by jfink5** [comment]
That looks like a separate issue.  Not synchronized is a problem between Enterprise Manager and Control-M Server.  That would explain why the run isn't working.  This likely has nothing to do with the Python Client.

**Comment by rbeker-BMC** [comment]
Python client behaves like Automation API, you have to use a user who has the ability to execute and browse folders and jobs. 
[What  permissions and privileges are needed to be defined in user security authorizations in order for a user to be able to consume all of the endpoints in Control-M Automation API?](https://community.bmc.com/s/article/What-permissions-and-privileges-are-needed-to-be-defined-in-user-security-authorizations-in-order-for-a-user-to-be-able-to-consume-all-of-the-endpoints-in-Control-M-Automation-API)
