### ISSUE TITLE
Add a condition to IfVariableValue

### ISSUE THREAD

**Issue by tvanderhey** [controlm/ctm-python-client#49]
When I created a job manually, in the Actions tab, On-Do Actions, I can select "Add/Remove Condition" in the Do drop down list. I do not see a way to do this with the Python classes. For example, in the if_list below, I would like to add a Condition when an IfVariableValue is true. Is there a way to do this?

job1.if_list.append(
    IfVariableValue('VariableValue',
                    variable_name='DONE',
                    variable_value='TRUE',
                    operator=IfVariableValue.Operator.StartsWith,
                    on_list=[ActionStopCyclicRun('SetToOk')]))

**Comment by jfink5** [comment]
Try this...

osJob.if_list.append(
    IfVariableValue('VariableValue_0',
                    variable_name='abc',
                    variable_value='123',
                    operator='StartsWith',
                    do_list=[EventAdd('Event:Add_0', event='abcdone')]
                    )
)

**Comment by tvanderhey** [comment]
That worked. Thanks.
