### ISSUE TITLE
101-HelloWorld Example Code - Missing Code Lines

### ISSUE THREAD

**Issue by altaiguy** [controlm/ctm-python-client#5]
Hello!

I tried to copy the code that is in the 101-HelloWorld example and there are missing lines of code for the example to operate properly.  The lines below are missing from the example and need to be added for the example to operate:

from ctm_python_client.core.bmc_control_m import CmJobFlow
from ctm_python_client.jobs.dummy import DummyJob

If the above are not included, errors are thrown for the documented code when that code is copied and executed.

**Comment by cmoraes-bmc** [comment]
Closing since new version has different examples/tutorials
