### ISSUE TITLE
Adding resource to a job using Python Client

### ISSUE THREAD

**Issue by spabbise** [controlm/ctm-python-client#50]
I am trying to add a control resource to a job using the below lines but its not working

myFirstCommandJob = JobCommand('DPS_NFJ1',
command='echo hello world', resource_list=[ResourceLock('lock1',lock_type=ResourceLock.LockType.Exclusive)])

Please help me on this

**Comment by spabbise** [comment]
So you want me to try like this?

resource_list=[ResourceLock('lock1',lock_type='Exclusive')]

**Comment by jfink5** [comment]
Yes

________________________________
Jon Fink
Principal Solution Engineer
DBA PreSales
Mobile

+1 239.821.8675
USA Florida.- Office at Home

[BMC—Run and Reinvent]<http://www.bmc.com/>
[BMC Communities]<https://communities.bmc.com/>
[Twitter]<https://twitter.com/bmcsoftware>
[Facebook]<https://www.facebook.com/bmcsoftware>
[YouTube]<http://www.youtube.com/user/BMCSoftwareBMCtv>
[LinkedIn]<http://www.linkedin.com/company/bmc-software>



From: spabbise ***@***.***>
Sent: Thursday, September 14, 2023 12:27 PM
To: controlm/ctm-python-client ***@***.***>
Cc: Fink, Jon ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [controlm/ctm-python-client] Adding resource to a job using Python Client (Issue #50)


So you want me to try like this?

resource_list=[ResourceLock('lock1',lock_type='Exclusive')]

**Comment by spabbise** [comment]
Still its not working, Build & Deploy is not taking that change to Control-M

**Comment by jfink5** [comment]
It worked for me.  So its possible you aren’t looking at it refreshed or something is getting crossed.  Here is some sample code that I used.


osCommand = "whoami && env"
osJob = JobCommand("CommandJob", command=osCommand)
osJob.resource_list = [ResourceLock("jfi-res4", lock_type='Exclusive')]
osJob.wait_for_events_list
workflow.add(osJob, inpath="jfi-workflow3")

Have you tried dumping your workflow to json and looking at it?  When I need to debug something that’s what I do.  And then I use “ctm build” with cli to deploy it.  In a debug scenario you will get better errors back when deploying with the cli.

with open("c:/temp/sendout.json", "w") as f:
    workflow.dump_json(f, indent=2)

ctm deploy c:\temp\sendout.json


________________________________
Jon Fink
Principal Solution Engineer
DBA PreSales
Mobile

+1 239.821.8675
USA Florida.- Office at Home

[BMC—Run and Reinvent]<http://www.bmc.com/>
[BMC Communities]<https://communities.bmc.com/>
[Twitter]<https://twitter.com/bmcsoftware>
[Facebook]<https://www.facebook.com/bmcsoftware>
[YouTube]<http://www.youtube.com/user/BMCSoftwareBMCtv>
[LinkedIn]<http://www.linkedin.com/company/bmc-software>



From: spabbise ***@***.***>
Sent: Thursday, September 14, 2023 12:33 PM
To: controlm/ctm-python-client ***@***.***>
Cc: Fink, Jon ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [controlm/ctm-python-client] Adding resource to a job using Python Client (Issue #50)


Still its not working, Build & Deploy is not taking that change to Control-M

**Comment by spabbise** [comment]
Is it mandatory to add "osJob.wait_for_events_list" in the script?

What is actually do?

**Comment by jfink5** [comment]
No.  wait_for_events_list is another way to specify IN conditions.  

Did you get past your deploy issue?  This problem is independent from the ctm-python-client itself.  Its possible that you have some other problem.  That's why I suggested dumping the workflow into a json file and use the ctm cli to run the deploy.  It will provide feedback on your problem.

**Comment by spabbise** [comment]
My deployment issue is fixed.
Dumping the workflow into a json file and using the ctm cli to run the deployment, helped me in fixing the issue.

Thanks @jfink5
