### ISSUE TITLE
Issue while selecting the Connection Profile in the Control-M database job using the Python Client

### ISSUE THREAD

**Issue by spabbise** [controlm/ctm-python-client#56]
I am using the below commands in my Python Client script to create a new Database Stored Procedure job in Control-M, But the code is not properly picking the connection_profile, due to that database type is missing and the job is not running(PFB)
![Screenshot 2023-10-31 at 5 07 13 PM](https://github.com/controlm/ctm-python-client/assets/137033157/cf074621-587c-4a70-bfa7-dfebd73acbcf)

mySecondDBJob = JobDatabaseStoredProcedure('DPS_SaiAnudeep_DB_PC_Job2',
connection_profile='CTMEM',
stored_procedure='CREATE_SCHEMA_OBJECTS',
schema='CTMEM',
package='*',
autocommit='N',
output_execution_log='Y',
output_sql_output='N',
sql_output_format='XML')

**Comment by rbeker-BMC** [comment]
You wrote it right, it's not a parameter taken at runtime. 
It's not a problem of the job Database Stored Procedure, it's a problem of the desk. 
The same problem can also be reproduced through the use of Automation API.

I recommend opening case in control-m through the correct channels.
