### ISSUE TITLE
Ability to chain jobs in different folders? 

### ISSUE THREAD

**Issue by loafob** [controlm/ctm-python-client#6]
Hello, I have perused the code, but it isn't clear to me whether it is possible to chain jobs that are in different folders.  Am I missing it somewhere? The requirement to supply a folder to the CmJobFlow.chain_jobs function tells me that it isn't supported.  Apologies if this is not appropriate!

**Comment by cmoraes-bmc** [comment]
Hi, indeed we don't support yet chaining jobs between different folders. We want to study the possibility of doing so however. 
Regards, and thank you for the feedback!
