### ISSUE TITLE
Workflow methods chain and connect look to be broken

### ISSUE THREAD

**Issue by jfink5** [controlm/ctm-python-client#70]
It looks like a bug was introduced recently.  When using chain or connect methods of Workflow object, then more than 1 eventsToAdd using the same Event name are generated in the json.  This does not pass the validation test and will not deploy to Control-M.

**Comment by rbeker-BMC** [comment]
Hi @jfink5, 
please use our latest release (version 2.2.3) of the [ctm-python-client](https://pypi.org/project/ctm-python-client/) for the resolution. 
Thank you for your patience and support!
