### ISSUE TITLE
Job dependencies do not deploy on Helix

### ISSUE THREAD

**Issue by xgiannak** [controlm/ctm-python-client#73]
## Reproduction steps
When using the python client to create a flow, with dependencies like
`t1_flow.connect(job1, job2)`
it is rendered with a construct like
```      "eventsToAdd_vNLTff1j": {
        "Type": "AddEvents",
        "Events": [
          {
            "Type": "Event:Out:Add",
            "Event": "StartFlow-TO-slow_bull"
          },
```
In a Helix environment, this causes an error on the "Type" line. Note that when the line is suppressed, the deploy happens correctly, and the dependencies are well defined.

## Environment
Helix Control-M 9.21.0.280
Python CLI ctm-python-client  2.2.1

Thanks and keep up the good work!

**Comment by rbeker-BMC** [comment]
Hi @xgiannak ,
Thank you for bringing this matter to our attention.
There is a fix related to this issue, please use the latest version of [ctm-python-client](https://pypi.org/project/ctm-python-client/).
