### ISSUE TITLE
RunApi get_job_output fails with HTTP 406

### ISSUE THREAD

**Issue by maxsatula** [controlm/ctm-python-client#8]
RunApi get_job_output fails with HTTP 406

```
clients.ctm_api_client.rest.ApiException: (406)
Reason: Not Acceptable
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'private', 'Expires': 'Wed, 31 Dec 1969 19:00:00 EST', 'Set-Cookie': 'JSESSIONID=*********************; Path=/automation-api/; Secure; HttpOnly', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, PUT', 'Access-Control-Allow-Headers': 'Authorization,Content-Type', 'Server': 'Jetty(9.2.z-SNAPSHOT)', 'Content-Type': 'text/json;charset=ISO-8859-1', 'Content-Length': '110', 'Date': 'Sat, 21 May 2022 18:03:28 GMT'})
HTTP response body: { "errors" : [ {"message":"Not Acceptable", "code" : "406", "uri" : "/run/job/***:***/output"} ]
  }
```

The problem seems to be in file `run_api.py` line 1845, an actual content-type is not listed

**Comment by maxsatula** [comment]
Despite error message says `Content-Type': 'text/json;charset=ISO-8859-1'`, an actual content type is `application/text`

**Comment by cmoraes-bmc** [comment]
Hi,
We are releasing a new version of the python client mid/end June which has a more user friendly monitoring of the run that should fix the issue. 

I will close the issue only when the new version will be released to let you know.

Thanks

**Comment by maxsatula** [comment]
@cmoraes-bmc thank you for the update, that would be nice. Current version is very counter-intuitive and makes more roadblocks than just writing code to call HTTP requests on my own.
As a side note, that would be really nice if the new version adopts async/await calls.

**Comment by cmoraes-bmc** [comment]
Hi @maxsatula  as i said before, i was waiting for the new version to go out to close the issue. Please check the new version of python client, it has support for basic monitoring actions like getting the output of a job. You can check a tutorial here: https://controlm.github.io/ctm-python-client/notebooks/monitoring.html
Thanks!
