### ISSUE TITLE
Jobs added via SubFolder do not pickup WorkflowDefaults

### ISSUE THREAD

**Issue by jfink5** [controlm/ctm-python-client#90]
When adding a SubFolder that includes a job_list, then the WorkflowDefaults do not make it down to the job level.

Example
```
workflow.add(SubFolder('sub_name',
     job_list=job_list),
     inpath='my_root_folder')
```

**Comment by RefaelBeker7** [comment]
Hi @jfink5,
The fix will be in the upcoming releases.
